name: GitHub Pages

on:
  push:
    branches: [ main ]
jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        NODE_ENV: production
        # This is set automatically by github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "jkeller52"
          git config user.email "jacobkeller52@gmail.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/jkeller52/personal-site.git
          gh-pages -d build
